[project]
name = "juegoauto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pyautogui>=0.9.54",
    "screeninfo>=0.8.1",
]
